### PR TITLE
Update Poker Hands Kata

### PR DESCRIPTION
**Pull request by MoeFarag**
The Flush example had a full house which would make Black win

### CODE REVIEW

**Comment by garora** [comment]
@MoeFarag - are you planning to write tests?

**Comment by MoeFarag** [comment]
@garora what do you mean? where do I add tests?

**Comment by shubyarora** [comment]
You can write tests by creating a separate folder in solution. Refer other tests.
Sent from my Intex Smartphone
On Jan 29, 2016 3:24 AM, Moe Farag <notifications@github.com> wrote:
@garora what do you mean? where do I add tests?

---

**Comment by MoeFarag** [comment]
Sure, I can add tests,, I'll do that when I have a free slot in a couple of
weeks,, swamped at the moment

**Comment by garora** [comment]
Makes sense! Appreciated

On Wed, Feb 3, 2016 at 10:35 PM, Moe Farag <notifications@github.com> wrote:

> Sure, I can add tests,, I'll do that when I have a free slot in a couple of
> weeks,, swamped at the moment
>
> On Fri, Jan 29, 2016 at 5:36 PM, Shuby Arora <notifications@github.com>
> wrote:
>
> > You can write tests by creating a separate folder in solution. Refer
> other
> > tests.
> > Sent from my Intex Smartphone
> > On Jan 29, 2016 3:24 AM, Moe Farag <notifications@github.com> wrote:
> > @garora what do you mean? where do I add tests?
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/garora/TDD-Katas/pull/22#issuecomment-176438782
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/garora/TDD-Katas/pull/22#issuecomment-176821653>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/garora/TDD-Katas/pull/22#issuecomment-179348658>.
>



-- 
Thanks & Regards,
Gaurav Arora

**Pull request merged**
